- name: Assert input parameter
  ansible.builtin.assert:
    that:
      - service is defined

- name: Add Service Tags to ansible groups var
  ansible.builtin.set_fact:
    ansible_inventory:
      groups: "{{ service.ServiceTags }}"

- name: Set Filter Expression
  ansible.builtin.set_fact:
    filter_exp: "\"RemoteAccessConsulService\" in Tags"

- name: Get Remote Access Connection Service of node with id = '{{ service.ID }}'
  ansible.builtin.uri:
    url: "{{ consul_url }}/v1/catalog/node-services/{{ service.Node }}?filter={{ filter_exp | urlencode() }}"
    method: GET
    status_code: 200, 404
    validate_certs: no
    headers:
      Authorization: "Bearer {{ consul_token }}"
  register: output_get_remote_access_service
  no_log: false

- set_fact:
    services: "{{ output_get_remote_access_service.json.Services }}"

- debug:
    msg: "Node with id='{{ service.ID }}' has no remote access service"
  when: services | length == 0

- name: Process found remote access service
  when: services | length != 0
  block:
    - name: Get remote access service
      ansible.builtin.uri:
        url: "{{ consul_url }}/v1/catalog/service/{{ services[0].Service }}"
        method: GET
        status_code: 200, 404
        validate_certs: no
        headers:
          Authorization: "Bearer {{ consul_token }}"
      register: output_connection_service
      no_log: false

    - name: Extract service object from consul response
      ansible.builtin.set_fact:
        remote_access_service: "{{ output_connection_service.json | first }}"

    - name: Get consul KV infos of remote_access_service
      ansible.builtin.include_tasks: helper/consul_kv/get_kv_of_service.yml
      vars:
        service_id: "{{ remote_access_service.ServiceID }}"

    - set_fact:
        credentialId: "{{ remote_access_service.ServiceMeta.credentialId }}"
        connection_type: "{{ remote_access_service.ServiceMeta.connectionType }}"

    - name: Set KV Path for vault call (Default)
      ansible.builtin.set_fact:
        vault_kv_path: "credentials/data/{{ credentialId }}"

    - name: Get Credentials linked to remote access service
      ansible.builtin.set_fact:
        vault_secret: "{{ lookup('hashi_vault', '{{ vault_lookup_base_info }} secret={{ vault_kv_path }}', as='raw') }}"

    - set_fact:
        credentialDataType: "{{ vault_secret.data.metadata.custom_metadata.credentialDataType }}"

    - set_fact:
        username: "{{ vault_secret.data.data.username }}"
        password: "{{ vault_secret.data.data.password }}"
      when: credentialDataType == "USERNAME_PASSWORD"

    - set_fact:
        privateKey: "{{ vault_secret.data.data.privateKey }}"
        publicKey: "{{ vault_secret.data.data.publicKey }}"
      when: credentialDataType == "KEY_PAIR"

    - name: Set Variables for add_host task (ssh)
      when: (connection_type | lower) == "ssh"
      ansible.builtin.set_fact:
        ansible_inventory:
          # GENERAL
          name: "{{ remote_access_service.Address }}"
          groups: "{{ (ansible_inventory.groups | default([])) + remote_access_service.ServiceTags + [connection_type] }}"
          ansible_connection: "ssh"
          ansible_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_shell_type: "sh"
          ansible_python_interpreter: '/usr/bin/python3'
          ansible_user: "{{ username }}"
          ansible_password: "{{ password }}"
          # BECOME
          ansible_become_user: ""
          ansible_become_pass: "{{ password }}"
          ansible_become_method: "sudo"
          # SSH
          ansible_ssh_user: "{{ username }}"
          ansible_ssh_password: "{{ password }}"
          ansible_ssh_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking\=no -o ServerAliveInterval=10'
          ansible_ssh_retries: 10
          # WinRM
          ansible_winrm_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_winrm_transport: "credssp"
          ansible_winrm_connection_timeout_sec: 30
          ansible_winrm_operation_timeout_sec: 120
          ansible_winrm_read_timeout_sec: 360
          ansible_winrm_server_cert_validation: ignore
          # PSRP
          ansible_psrp_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_psrp_connection_timeout: 30
          ansible_psrp_operation_timeout: 120
          ansible_psrp_read_timeout: 360
          ansible_psrp_reconnection_retries: 10
          ansible_psrp_cert_validation: ignore

    - name: Set Variables for add_host task (WinRM)
      when: (connection_type | lower) == "winrm"
      ansible.builtin.set_fact:
        ansible_inventory:
          # GENERAL
          name: "{{ remote_access_service.Address }}"
          groups: "{{ (ansible_inventory.groups | default([])) + remote_access_service.ServiceTags + [connection_type] }}"
          ansible_connection: "psrp"
          ansible_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_shell_type: ""
          ansible_python_interpreter: '/usr/bin/python3'
          ansible_user: "{{ username }}"
          ansible_password: "{{ password }}"
          # BECOME
          ansible_become_user: "{{ username }}"
          ansible_become_pass: "{{ password }}"
          ansible_become_method: "runas"
          # SSH
          ansible_ssh_user: "{{ username }}"
          ansible_ssh_password: "{{ password }}"
          ansible_ssh_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking\=no -o ServerAliveInterval=10'
          ansible_ssh_retries: 10
          # WinRM
          ansible_winrm_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_winrm_transport: "credssp"
          ansible_winrm_connection_timeout_sec: 30
          ansible_winrm_operation_timeout_sec: 120
          ansible_winrm_read_timeout_sec: 360
          ansible_winrm_server_cert_validation: ignore
          # PSRP
          ansible_psrp_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_psrp_connection_timeout: 30
          ansible_psrp_operation_timeout: 120
          ansible_psrp_read_timeout: 360
          ansible_psrp_reconnection_retries: 10
          ansible_psrp_cert_validation: ignore

    - name: Set Variables for add_host task (win-ssh)
      when: (connection_type | lower) == "winssh"
      ansible.builtin.set_fact:
        ansible_inventory:
          # GENERAL
          name: "{{ remote_access_service.Address }}"
          groups: "{{ (ansible_inventory.groups | default([])) + remote_access_service.ServiceTags + [connection_type] }}"
          ansible_connection: "ssh"
          ansible_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_shell_type: "cmd"
          ansible_python_interpreter: '/usr/bin/python3'
          ansible_user: "{{ username }}"
          ansible_password: "{{ password }}"
          # BECOME
          ansible_become_user: "{{ username }}"
          ansible_become_pass: "{{ password }}"
          ansible_become_method: "runas"
          # SSH
          ansible_ssh_user: "{{ username }}"
          ansible_ssh_password: "{{ password }}"
          ansible_ssh_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_ssh_common_args: '-o StrictHostKeyChecking\=no -o ServerAliveInterval=10'
          ansible_ssh_retries: 10
          # WinRM
          ansible_winrm_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_winrm_transport: "credssp"
          ansible_winrm_connection_timeout_sec: 30
          ansible_winrm_operation_timeout_sec: 120
          ansible_winrm_read_timeout_sec: 360
          ansible_winrm_server_cert_validation: ignore
          # PSRP
          ansible_psrp_port: "{{ remote_access_service.ServicePort | default(0, true) }}"
          ansible_psrp_connection_timeout: 30
          ansible_psrp_operation_timeout: 120
          ansible_psrp_read_timeout: 360
          ansible_psrp_reconnection_retries: 10
          ansible_psrp_cert_validation: ignore
